---
title: "My page"
author: "Marcelo Ventura"
date: "09/04/2018"
output: html_document
---


## Welcome!

This is my personal webpage. Here you will find common, uncommon, and crazy information :)

## Common information

My name is Marcelo Ventura, and I've got a Msc. in Applied Economics. My personal, academic, and profesional interests are: R language, social media, Data mining, statistics, economics, Monte Carlo simulations. 

I've published works about youtube, http://ssystem08.upis.br/repositorio/media/revistas/revista_multipla/multipla41.pdf, IMDb.com, http://repositorio.bc.ufg.br/tede/handle/tede/8278. Also, I'm going to publish a work about criptocurrencies. 

I would be amazed if I could find you in social media like Linked-in, https://www.linkedin.com/in/marcelo-ventura-8542a9a6/, Strava, https://www.strava.com/athletes/19622799, Twitter, www.twitter.com/marcelosventura, and Kaggle, https://www.kaggle.com/marceloventura.

If you are old school, don't worry. I'm the one with the force at marcelos.ventura@gmail.com powered by www.helloastro.com.

My cell number is +5562993463125.

## Uncommon information

To be continued.....

# Crazy information

I avoid discussions about politics in Brazil, I love running.
